package com.myspace.reinsuranceworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AddressDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AddressDetails() {
    }




}