package com.myspace.reinsuranceworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AddressDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Address Line 1")
	private java.lang.String addressLine1;
	@org.kie.api.definition.type.Label("Address Line 2")
	private java.lang.String addressLine2;
	@org.kie.api.definition.type.Label("Street")
	private java.lang.String street;
	@org.kie.api.definition.type.Label("City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label("State")
	private java.lang.String state;
	@org.kie.api.definition.type.Label("Country")
	private java.lang.String country;
	@org.kie.api.definition.type.Label("Pin Code")
	private java.lang.Integer pinCode;

	@org.kie.api.definition.type.Label(value = "Address ID")
	private java.lang.String addressId;

	@org.kie.api.definition.type.Label(value = "Address Type")
	private java.lang.String addressType;

	public AddressDetails() {
	}

	public java.lang.String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(java.lang.String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public java.lang.String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(java.lang.String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public java.lang.String getStreet() {
		return this.street;
	}

	public void setStreet(java.lang.String street) {
		this.street = street;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.Integer getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(java.lang.Integer pinCode) {
		this.pinCode = pinCode;
	}

	public java.lang.String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(java.lang.String addressId) {
		this.addressId = addressId;
	}

	public java.lang.String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(java.lang.String addressType) {
		this.addressType = addressType;
	}

	public AddressDetails(java.lang.String addressLine1,
			java.lang.String addressLine2, java.lang.String street,
			java.lang.String city, java.lang.String state,
			java.lang.String country, java.lang.Integer pinCode,
			java.lang.String addressId, java.lang.String addressType) {
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.street = street;
		this.city = city;
		this.state = state;
		this.country = country;
		this.pinCode = pinCode;
		this.addressId = addressId;
		this.addressType = addressType;
	}

}