package com.myspace.reinsuranceworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String filed1;

	public TestDataObject() {
	}

	public java.lang.String getFiled1() {
		return this.filed1;
	}

	public void setFiled1(java.lang.String filed1) {
		this.filed1 = filed1;
	}

	public TestDataObject(java.lang.String filed1) {
		this.filed1 = filed1;
	}

}