package com.myspace.reinsuranceworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testDataObjectPrincy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String customerName;

	public testDataObjectPrincy() {
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public testDataObjectPrincy(java.lang.String customerName) {
		this.customerName = customerName;
	}

}